name: Update Playwright Snapshots
on:
  workflow_dispatch:
jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Update snapshots
        run: npx playwright test --update-snapshots
      - name: Upload snapshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-linux-snapshots
          path: |
            **/*-snapshots/**
